apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-reclaim
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: xfs
    volumeHandle: vol-0b3e8484cb57af7cb
    volumeAttributes:
      type: gp3
      iops: "300"
      throughput: "125"
      encrypted: "true"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-west-1b
