apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-snapshot-restored-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: static-snapshot-demo
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
