apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-reclaim-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-reclaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
