apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: default
spec:
  containers:
    - name: app
      image: debian:latest
      command: ["/bin/bash"]
      args:
        ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-restore
          mountPath: /data
  volumes:
    - name: persistent-restore
      persistentVolumeClaim:
        claimName: ebs-claim
