apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: camiseta80@gmail.com
    server: https://acme.zerossl.com/v2/DV90
    privateKeySecretRef:
      name: cloudflare
    externalAccountBinding:
      keyID: qWeoinRAxoe6-fjMs1dvuA
      keySecretRef:
        name: zero-ssl-eabsecret
        key: secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
