apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICAgICAiZ2hjci5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJhbUZ5ZG1selltOTBNREU2WjJod1gwVmhNMWRNTWpkS1RqQjVjMEYyVUZseGVHOXFUa2xKYVZKc1NHSkxTakIzVm1WUlZnPT0iCiAgICAgICAgICAgIH0KICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson
