apiVersion: v1
kind: Secret
metadata:
  name: zero-ssl-eabsecret
  namespace: cert-manager
data:
  secret: cHdRbDR0akdMYmVzVUMxdmpuX1ZHVDdiR0ZCWV9Ic1gwbF94TGZpU0pUaC1zM1Rndk15THJnZEtKcHRCQUtmZk5ZNlFfLWZ3QWNuMFhQa0NmRFlpUUE=
