configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: kube-jarvis-velero
      config:
        region: us-west-1

  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-west-1

initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.10.1
  volumeMounts:
  - mountPath: /target
    name: plugins
