apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-virtualservice
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/internal-gateway
  http:
  - match:
    - uri:
        prefix: /api/{ pais, persona, ciudad }
    - uri:
        prefix: /
    route:
    - destination:
        host: mi-servicio.default.svc.cluster.local
        subset: v1
        port:
          number: 8080
